CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch \
	--master_port 10090 --nproc_per_node=1  oscar/zeroshot/refcoco_cpt.py \
	--model_name_or_path pretrained_models/image_captioning/pretrained_base \
	--eval_model_dir pretrained_models/image_captioning/pretrained_base \
	--do_train \
	--test_dir ../prompt_feat/output/refcoco/cpt/inference/refcoco+_ \
	--do_lower_case \
	--add_od_labels \
	--per_gpu_train_batch_size 8 \
	--per_gpu_eval_batch_size 4 \
	--num_train_epochs 60 \
	--tie_weights \
	--freeze_embedding \
        --label_smoothing 0.1 \
    	--drop_worst_ratio 0.2 \
	--drop_worst_after 20000 
